[build]
  command = "" # הוספנו את השורה הזאת כדי לבטל את Hugo
  publish = "."

[[redirects]]
  from = "/faculty"
  to = "/faculty.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/skills"
  to = "/skills.html"
  status = 200
